// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgVaLrIIdb4B0p-qKygPFPHxtKRgWiyKI',
    appId: '1:910277914750:web:1063c8dd15bfa2b3ee282f',
    messagingSenderId: '910277914750',
    projectId: 'die-menus-6897c',
    authDomain: 'die-menus-6897c.firebaseapp.com',
    storageBucket: 'die-menus-6897c.appspot.com',
    measurementId: 'G-X81XKLXQ5Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeyOCrSpH4Y7mWBeut5sG-GnAql8BdQBI',
    appId: '1:910277914750:android:7bab247f7c13fd60ee282f',
    messagingSenderId: '910277914750',
    projectId: 'die-menus-6897c',
    storageBucket: 'die-menus-6897c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2AFfLSGLzoVmS6HAFy9RWK6nQtZrOkic',
    appId: '1:910277914750:ios:91d03179c09bd34bee282f',
    messagingSenderId: '910277914750',
    projectId: 'die-menus-6897c',
    storageBucket: 'die-menus-6897c.appspot.com',
    iosBundleId: 'com.example.projetoAplicado',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2AFfLSGLzoVmS6HAFy9RWK6nQtZrOkic',
    appId: '1:910277914750:ios:91d03179c09bd34bee282f',
    messagingSenderId: '910277914750',
    projectId: 'die-menus-6897c',
    storageBucket: 'die-menus-6897c.appspot.com',
    iosBundleId: 'com.example.projetoAplicado',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgVaLrIIdb4B0p-qKygPFPHxtKRgWiyKI',
    appId: '1:910277914750:web:6b24cd491ec5f9fcee282f',
    messagingSenderId: '910277914750',
    projectId: 'die-menus-6897c',
    authDomain: 'die-menus-6897c.firebaseapp.com',
    storageBucket: 'die-menus-6897c.appspot.com',
    measurementId: 'G-PM4P6XZ0ZF',
  );

}